{% set name = "ngboost" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a582f63c4ddfcb131bac4c8bb3c861a717ada677862c9c503adb94888e11eb0f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7.1,<3.11
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7.1,<3.11
    - numpy >=1.21.2
    - scipy >=1.7.2
    - scikit-learn >=1.0.2
    - tqdm >=4.3
    - lifelines >=0.25
    - pandas >=1.3.5
    - flake8 >=5.0.4,<5.1.0

test:
  imports:
    - ngboost
    - ngboost.distns
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/stanfordmlgroup/ngboost
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Natural Gradient Boosting for Probabilistic Prediction

  description: |
    'ngboost is a Python library that implements Natural Gradient Boosting,
    as described in "NGBoost:
    Natural Gradient Boosting for Probabilistic Prediction".
    It is built on top of Scikit-Learn,
    and is designed to be scalable and modular
    with respect to choice of
    proper scoring rule, distribution, and base learners.'


  doc_url: https://github.com/stanfordmlgroup/ngboost
  dev_url: https://github.com/stanfordmlgroup/ngboost

extra:
  recipe-maintainers:
    - ericmjl
    - avati
    - synapticarbors
