{% set name = "ngboost" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b43f9fd7eea870974f8f1c3c023517f1c4321074b750cb3a7900bfd3a41e22f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }},<3.13
    - numpy >=1.21.2
    - scipy >=1.7.2
    - scikit-learn >=1.0.2
    - tqdm >=4.3
    - lifelines >=0.25
    - pandas >=1.3.5
    - flake8 >=5.0.4,<5.1.0

test:
  imports:
    - ngboost
    - ngboost.distns
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/stanfordmlgroup/ngboost
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Natural Gradient Boosting for Probabilistic Prediction

  description: |
    'ngboost is a Python library that implements Natural Gradient Boosting,
    as described in "NGBoost:
    Natural Gradient Boosting for Probabilistic Prediction".
    It is built on top of Scikit-Learn,
    and is designed to be scalable and modular
    with respect to choice of
    proper scoring rule, distribution, and base learners.'


  doc_url: https://github.com/stanfordmlgroup/ngboost
  dev_url: https://github.com/stanfordmlgroup/ngboost

extra:
  recipe-maintainers:
    - ericmjl
    - avati
    - synapticarbors
