{% set name = "ngboost" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 575c0d0c3aec6e1ca6d424d9b19e3be0c1d84640bce5beb226975b50358df892

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - absl-py
    - autograd
    - autograd-gamma
    - cycler
    - fastcache
    - future
    - joblib
    - kiwisolver
    - lifelines
    - matplotlib-base
    - numpy
    - opt-einsum
    - pandas
    - protobuf
    - pyparsing
    - python-dateutil
    - pytz
    - scikit-learn
    - scipy
    - six
    - tqdm


test:
  imports:
    - ngboost

about:
  home: https://github.com/stanfordmlgroup/ngboost
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Natural Gradient Boosting for Probabilistic Prediction

  description: |
    'ngboost is a Python library that implements Natural Gradient Boosting,
    as described in "NGBoost:
    Natural Gradient Boosting for Probabilistic Prediction".
    It is built on top of Scikit-Learn,
    and is designed to be scalable and modular
    with respect to choice of
    proper scoring rule, distribution, and base learners.'


  doc_url: https://github.com/stanfordmlgroup/ngboost
  dev_url: https://github.com/stanfordmlgroup/ngboost

extra:
  recipe-maintainers:
    - ericmjl
    - avati
